apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-argocd-vault
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: example-secret

--- 

kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "kv/data/test"
type: Opaque
stringData:
  sample-secret: <hello>
